packages:
  - 'packages/*'

allowBuilds:
  electron: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.2'
  - '@tanstack/vue-query@5.101.2'
  - '@hugo-ui/shadcn-vue@0.2.0-local.1782765559315'
